### ISSUE TITLE
选择一个省份之后如何清空选项？

### ISSUE THREAD

**Issue by terranc** [iview/iview-area#13]
RT

**Comment by lison16** [comment]
数组赋为空数组

**Comment by terranc** [comment]
我不是说程序上怎么处理，是交互上，界面上选择了省份之后，下一步要如何操作才能置为不选的状态呢

**Comment by lison16** [comment]
交互是你们设计考虑的

**Comment by terranc** [comment]
。。。。
我们假设这么个场景，看看这个东西怎么用。
一组筛选功能，选择省市区后点击『筛选』按钮筛选数据，然而用户这个时候选择了『上海』，这时候用户自己发现不需要筛选省市区了，这个时候如何撤消刚才下拉框里选择的『上海』呢？
