### ISSUE TITLE
选择直辖市时，数据不会变化

### ISSUE THREAD

**Issue by taosang1992** [iview/iview-area#19]
view-area 插件在使用的时候，如果是选择直辖市，数据就不变
请注意：已经选了天津，但是数据还是北京
![2018-01-06 7 35 27](https://user-images.githubusercontent.com/21000340/34639332-15458390-f319-11e7-885a-743bf28198bc.png)
官方Demo可以直接重现：https://iview.github.io/iview-admin/#/component/area-linkage

**Comment by lison16** [comment]
最新版已经修复
