### ISSUE TITLE
v-modal双向绑定不起作用

### ISSUE THREAD

**Issue by LeToNode** [iview/iview-area#20]
我在弹窗iview的modal中使用area组件，
就是用户表格单向选择编辑，然后弹窗有编辑表格，这个时候area的数据才通过ajax请求获取到本地。

```
<al-selector v-model="workUnitInfo.cityCodes" data-type="code" gutter="5" level="2" size="small"/>
```

发现v-modal不起作用，通过vue的开发者工具是能看到value有内容的。
能否是不是组件数据变更没有触发？

**Comment by lison16** [comment]
稍后确认下

**Comment by terranc** [comment]
我也发现有这个问题

**Comment by lison16** [comment]
刚刚修复，升级到2.5.15

**Comment by TonyLuo** [comment]
新版1.5.15报错
iview-area.js?0465:1 Uncaught TypeError: r is not a function
    at Object.eval (iview-area.js?0465:1)
    at e (iview-area.js?0465:1)
    at Object.eval (iview-area.js?0465:1)
    at e (iview-area.js?0465:1)
    at Object.eval (iview-area.js?0465:1)
    at e (iview-area.js?0465:1)
    at Object.eval (iview-area.js?0465:1)
    at e (iview-area.js?0465:1)
    at Object.eval (iview-area.js?0465:1)
    at e (iview-area.js?0465:1)

**Comment by lison16** [comment]
已紧急修复，谢谢，升级到1.5.16

**Comment by TonyLuo** [comment]
升级到1.5.16还是没办法通过指定值来初始化选择某个地区
```
area  = [ {
        "code": "110000",
        "name": "北京市"
      }],
 <al-cascader v-model="area"  level="0"></al-cascader>
```

**Comment by lison16** [comment]
昨天说的是selecter的没法指定初始值，我就没测另一个，我再看看

**Comment by lison16** [comment]
升级到1.5.17，有问题再提哈

**Comment by TonyLuo** [comment]
1.5.17还是不行.
下面这个简单的例子都没法正常初始化

```
<template>
    <al-selector v-model="res_s" level="0"/>
    <al-cascader v-model="res_c" level="0"/>
</template>
<script>
    export default {
        data () {
            return {
                res_s:  [ {
        "code": "110000",
        "name": "北京市"
      }],
                res_c:  [ {
        "code": "110000",
        "name": "北京市"
      }]
            }
        }
    }
</script>
```

**Comment by lison16** [comment]
@TonyLuo 暂时没有判断传入的数组元素为对象的情况，只能传入名称或code中的一种

**Comment by xtStudent** [comment]
被这个bug困扰好久，还好过来逛了下，升级到最新版就好了，感谢大大

**Comment by bulolo** [comment]
你好，现在最新你的还是这种情况，无法双向绑定
