### ISSUE TITLE
设置默认值失效

### ISSUE THREAD

**Issue by nicholasyum** [iview/iview-area#3]
如图，res1在data初始化值的话 区域可以设置默认值，但是resDefault在mounted的时候初始化值 区域就绑定不了默认数据
![untitled](https://user-images.githubusercontent.com/5977285/33055441-a4e4752a-ceba-11e7-8c44-7d965f221a89.png)

**Comment by lison16** [comment]
升级到@1.5.9版本

**Comment by lison16** [comment]
忘了修改al-cascader了，稍等

**Comment by lison16** [comment]
现已修复
