### ISSUE TITLE
快速连续多次点击输入框时下拉框移位

### ISSUE THREAD

**Issue by L-sizhong** [iview/iview-area#4]
使用选择器类型或者级联类型时，当在页面上快速连续多次点击该插件的输入框，在大概第8次左右，下拉框会移位，出现在整个页面的左上侧

注意，一定要快速连续点击输入框

![default](https://user-images.githubusercontent.com/13596098/33198421-fac6342a-d125-11e7-8ba7-2970a5ddb7cc.png)

**Comment by lison16** [comment]
刚刚看了下，这个是iview的cascader这个组件本身的问题，我会和Aresn说一下的，您最好能到iview的github主页提个issue

**Comment by L-sizhong** [comment]
好的，谢谢解答
