### ISSUE TITLE
台湾省选项无法选择

### ISSUE THREAD

**Issue by L-sizhong** [iview/iview-area#5]
级联类型时，台湾省选项无法选中

![default](https://user-images.githubusercontent.com/13596098/33198904-c0b15fc8-d128-11e7-8b11-b1a07245533d.png)

**Comment by lison16** [comment]
刚刚看了下，是因为area-data没有台湾省的子级数据的原因

**Comment by L-sizhong** [comment]
好的，谢谢解答

**Comment by lison16** [comment]
由于没有台湾省没有子级数据，还有两个特别行政区也不是有4级数据，导致报错，现已解决，升级到1.5.11即可
