### ISSUE TITLE
Cascader默认数据异步加载的问题

### ISSUE THREAD

**Issue by joneqian** [iview/iview-area#9]
我通过ajax异步获取数据来设置Cascader的时候没有触发组件的显示更新，如果直接在data里设置绑定值的时候是没有问题的！！！建议Cascader外抛一个方法，让外部通过ref来调用控制更新显示！

**Comment by leemove** [comment]
我感觉这个还是很有必要的.,我写了一个修改数据可以直接更新视图的功能...提pr被closed了....

**Comment by joneqian** [comment]
查看了源代码，发现可以手动设置默认值，代码如下：
this.$refs.alCascader.setDefaultValue();

**Comment by dafeng17** [comment]
请问我cDefault=['130000', '130700', '130730']，怎么用this.$refs.alCascader.setDefaultValue();设置呢？
